const filterActions = {
  SORT: "SORT",
  TOGGLE_OUT_OF_STOCK: "TOGGLE_OUT_OF_STOCK",
  ADD_CATEGORY: "ADD_CATEGORY",
  SET_RATING: "SET_RATING",
  SET_RANGE: "SET_RANGE",
  SET_MIN: "SET_MIN",
  SET_MAX: "SET_MAX",
  CLEAR: "CLEAR",
};
export { filterActions };
